### ISSUE TITLE
The resolve method of dnssrv\subscriber may get very large slice

### ISSUE THREAD

**Issue by jizhuozhi** [luraproject/lura#534]
**Describe the bug**

The resolve method of dnssrv\subscriber may get very large fragments. If the weight of the DNS-resolved address is very large, and the number of resolved records is very large.

**To Reproduce**

Use a simple unit test, set the weight of the address to 65535, and add enough records
```go
func TestSubscriber_ResolveVeryLarge(t *testing.T) {
	var srvSet []*net.SRV
	for i := 0; i < 100; i++ {
		srvSet = append(srvSet, &net.SRV{
			Port:   uint16(80 + i),
			Target: "127.0.0.1",
			Weight: 65535,
		})
	}
	lookupFunc := func(service, proto, name string) (cname string, addrs []*net.SRV, err error) {
		return "cname", srvSet, nil
	}
	s := NewDetailed("large.example.tld", lookupFunc, 1*time.Second)
	hosts, _ := s.Hosts()
	if len(hosts) != 65535*100 {
		t.Errorf("Excepted %d, but %d", 65535*100, len(hosts))
	}
}
```

**Expected behavior**

When we are using Weighted Round Robin loadbalancer, the number of memory occupied should only be related to the number of parsed SRVs, and should not have different memory usage with different weights, such as the EDF algorithm (as [mosn](https://github.com/mosn/mosn/blob/master/pkg/upstream/cluster/edf.go) or [nginx](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_upstream_round_robin.c#L49) used)

**Comment by jizhuozhi** [comment]
And if the weights are all large and the difference is not big (for example, all 65535), it seems that the same upstream server will be accessed continuously for a continuous period of time, which does not play a role in load balancing.

**Comment by kpacha** [comment]
all the components related to hot paths are optimized for latency and memory allocation. memory consumption is also important but secondary. that's why we translate the records into an array instead of using a priority queue/heap.

on the other hand, you have 2 great points:
- your example consumes too much memory
- for a large sets, the list should be shuffled

Thanks to your input we've improved the resolution strategy in order to add some compaction process before caching the result. thanks for the heads up!

**Comment by jizhuozhi** [comment]
Thank you for your answer, it is true that the benefit of using space for time for load balancers is very large, especially in the case of current machine memory redundancy.

However, thanks to the complete binary tree nature of the heap, on a huge cluster (taking 1,000 nodes as an example), using a well-designed heap for `peek` and `fix` operations will only increase 10 comparison and assignment operations compared to the self-incrementing pointer, and This number grows logarithmically. I think this overhead is worth it compared to the OOM risk

**Comment by jizhuozhi** [comment]
I will not use heap to submit PR, looking forward to your solution!

**Comment by kpacha** [comment]
we added two compaction strategies:
- if there are more than 100 entries, scale the values (https://github.com/luraproject/lura/blob/v2.0.0-dev/sd/dnssrv/subscriber.go#L163-L182)
- calculate the gcd and divide the set by it (https://github.com/luraproject/lura/blob/v2.0.0-dev/sd/dnssrv/subscriber.go#L150-L158)

with the new implementation, your example is resolved as an array of 100 positions, all with different values.

you can also check the new tests or the updated documentation (https://github.com/devopsfaith/krakend-documentation/commit/bfd54c577e2e463ed802daba4f90076a9bca7d26)

**Comment by jizhuozhi** [comment]
Aha! Thanks for your answer, it's time to go to bed now in China, so I simply looked at the code and had some suggestions.

GCD may seem like a good choice, using GCD to scale the values means we want to control the size of slice to the minimum positive period.

But there are still extreme exceptions: All elements are mutually reinforcing. It is not even necessary to say that all elements are mutually exclusive, as long as one element is mutually identical to all elements, the conditions are met.

So, in my opinion, GCD is a method that can reduce the length of arrays, but it does not solve our core problem: **in the case of the number of elements, our memory ceiling changes as weight changes**

I also want to say this solution before sleeping that we could use a threshold to control whether use the expand array  or heap. This introduces overhead caused by abstraction, but we can limit the problem of too much memory

**Comment by jizhuozhi** [comment]
For extreme exceptions I would add a theorem: for two numbers that are greater than 1, there is always n and n+1 mutually exclusive, means GCD(n, n+1) = 1.

This is common, and users often add or subtract 1 from a host in order to adjust its weight.

**Comment by jizhuozhi** [comment]
The above code seems to bring the wrong result
```go
func TestSubscriber_Mutually(t *testing.T) {
	var srvSet = make([]*net.SRV, 0)
	for i := 0; i < 2; i++ {
		srvSet = append(srvSet, &net.SRV{
			Port:   uint16(80 + i),
			Target: "127.0.0.1",
			Weight: uint16(i + 1),
		})
	}
	srvSet[0].Weight--
	lookupFunc := func(service, proto, name string) (cname string, addrs []*net.SRV, err error) {
		return "cname", srvSet, nil
	}
	s := NewDetailed("large.example.tld", lookupFunc, 1*time.Second)
	hosts, _ := s.Hosts()
	if !(len(hosts) > 1) {
		t.Errorf("Excepted at least 2 hosts, but %d", len(hosts))
	}
}
```
In this case, I wanted to test for arrays with interstitial elements not working, but I found that when the elements are 1 and 2, they are already wrong
```
=== RUN   TestSubscriber_Mutually
    subscriber_test.go:218: Excepted at least 2 hosts, but 1
--- FAIL: TestSubscriber_Mutually (0.00s)
```

**Comment by jizhuozhi** [comment]
The fix code in [v2.0.0-dev](https://github.com/luraproject/lura/blob/v2.0.0-dev/sd/dnssrv/subscriber.go#L163-L182) doesn't seem to fix this and introduces other problems
```go
func TestSubscriber_Mutually(t *testing.T) {
	var srvSet = make([]*net.SRV, 0)
	for i := 0; i < 100; i++ {
		// All elements are mutually, it should expand all elements to slice with the length SUM(1, 2, ... , 100)
		// weights := 1, 2, 3, 4, ... , 99, 100
		// GCD(weights) = GCD([..., GCD(99, 100)]) = GCD([..., 1]) = 1
		srvSet = append(srvSet, &net.SRV{
			Port:   uint16(80 + i),
			Target: "127.0.0.1",
			Weight: uint16(i + 1),
		})
	}
	lookupFunc := func(service, proto, name string) (cname string, addrs []*net.SRV, err error) {
		return "cname", srvSet, nil
	}
	s := NewDetailed("large.example.tld", lookupFunc, 1*time.Second)
	hosts, _ := s.Hosts()
	// There is used to check at least 100 hosts, cause we have 100 different hosts.
	if !(len(hosts) > 100) {
		t.Errorf("Excepted at least %d hosts, but %d", 100, len(hosts))
	}
}
```

According to the theoretical value above, we should get 5050 elements, at least we should get 100 elements because we have 100 different hosts, but in reality we only get 50 elements
```console
=== RUN   TestSubscriber_Mutually
    subscriber_test.go:217: Excepted at least 3 hosts, but 50
--- FAIL: TestSubscriber_Mutually (0.00s)
```
